<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Maprom Database</title>

  <!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
<h4>Maprom Database</h4>
<p>This is a autogenerated email from the Maprom database server</p>
<div>
    Total number of registered users is: {{ $count }}
</div>
<div>
    Total number of Romani households today is: {{ $ten }}
</div>
<div>
    Total number of Roms today is: {{ $romstotal }}
</div>
<div> Open statistics click <a href="https://insert.maprom.se/statistics">here</a>!
</div>


</body>
</html>
